#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=CheckEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=snellius-scripts/slurm_output_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Create environment - only needed the first time
# conda env create -f environment.yml

# Activate your environment
source activate MoE

# Check whether the GPU is available
srun python -uc "import torch; print('GPU available?', torch.cuda.is_available())"