#!/bin/bash
#SBATCH --job-name=build_moe_env
#SBATCH --partition=rome
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=01:00:00
#SBATCH --output=/gpfs/home5/aramautar2/projects/MoE-ShapeRefine-MedicalSeg/medSAM-stage1/slurm_build_moe_env_%j.out

set -euo pipefail

module purge
module load 2024
module load Anaconda3/2024.06-1

source /sw/arch/RHEL9/EB_production/2024/software/Anaconda3/2024.06-1/etc/profile.d/conda.sh

cd /gpfs/home5/aramautar2/projects/MoE-ShapeRefine-MedicalSeg

echo "job id  : ${SLURM_JOB_ID}"
echo "host    : $(hostname)"
echo "start   : $(date)"

conda env create -f environment.yml

echo "end : $(date)"
conda env list
